name: My variables
on: workflow_dispatch
permissions: read-all
env:
  MY_VARIABLE: Hello, GitHub Actions!
jobs:
  var-greeting:
    runs-on: ubuntu-latest
    env:
      SECRET: ${{ secrets.DEMO_SECRET}}
    steps:
      - name: Print vars
        run: |
          echo "$DEMO_SECRET"
          echo "$MY_VARIABLE"
