name: My variables
on: worflow_dispatch
env:
  MY_VARIABLE: Hello, GitHub Actions!

jobs:
  var-greeting:
    runs-on: ubuntu-latest
    env:
      SECRET: ${{ secrets.DEMO_SECRET}}
    steps:
      - name: Print vars
        run: echo "$MY_VARIABLE. Secret var: $DEMO_SECRET"
